#!/bin/bash

# --------------------------------------- Prerequisite --------------------------------------------
# 1. byzanz 
#		sudo dnf copr enable vishalvvr/byzanz	# for fedora
#		sudo dnf install byzanz -y
# 2. xrectsel
#		pip install python-xrectsel --user
# -------------------------------------------------------------------------------------------------

TIME=$(date +"%Y-%m-%d-%H%M%S")
FOLDER="$HOME/Pictures"
DELAY=3

# Notifcation sound
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
}

# Start recording with byzanz-record and xrectsel
recording_start() {
    # Find region with xrectsel
    sleep 1   
    REGION=$(xrectsel -f "-x %x -y %y -w %w -h %h")

    notify-send "Screencast:" "recording will start in $DELAY seconds."
    sleep $DELAY
    beep
	# start recording with byzanz recorder
    byzanz-record --cursor --exec 'sleep 1000000' --delay=1 ${REGION} "$FOLDER/screencast-$TIME.gif"
}

# Stop recording
recording_stop() {
    killall sleep
    beep
    notify-send "Screencast:" "saved to $FOLDER/screencast-$TIME.gif."
}


if pgrep -x sleep >/dev/null
then
    recording_stop
else
    recording_start
fi
